In [1]:
# from __future__ import print_function
import torch

### 1. Tensors
- Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [2]:
# Uninitialized array
x = torch.empty(5, 3)
print(x)

tensor([[ 3.0245e+35,  1.4153e-43,  4.6058e-38],
        [ 3.4438e-41,  2.9147e-43,  0.0000e+00],
        [-2.5270e+24,  4.5811e-41, -1.9227e+02],
        [ 4.5811e-41,  0.0000e+00,  7.0065e-45],
        [-4.7915e+24,  4.5811e-41, -4.7915e+24]])


In [3]:
x

tensor([[ 3.0245e+35,  1.4153e-43,  4.6058e-38],
        [ 3.4438e-41,  2.9147e-43,  0.0000e+00],
        [-2.5270e+24,  4.5811e-41, -1.9227e+02],
        [ 4.5811e-41,  0.0000e+00,  7.0065e-45],
        [-4.7915e+24,  4.5811e-41, -4.7915e+24]])

In [4]:
type(x)

torch.Tensor

In [4]:
# Random initialized array or matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.8690, 0.5917, 0.0377],
        [0.4982, 0.5919, 0.2020],
        [0.6017, 0.7287, 0.9890],
        [0.8774, 0.5035, 0.3504],
        [0.0927, 0.2968, 0.9060]])


In [5]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x) 

tensor([[ 0.2191,  0.3047, -0.9346],
        [ 0.6543,  0.2372,  0.0234],
        [ 0.5261,  0.6155, -0.1585],
        [-0.2751, -0.2340,  2.4734],
        [ 0.9938, -0.8391,  0.3855]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [12]:
x.shape

torch.Size([5, 3])

### 2. Operations

In [13]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)

tensor([[0.7704, 0.2157, 0.5113],
        [0.0395, 0.0694, 0.5740],
        [0.8084, 0.4592, 0.6681],
        [0.6030, 0.1920, 0.4003],
        [0.0042, 0.7863, 0.8625]])
tensor([[0.2968, 0.8698, 0.9908],
        [0.6065, 0.7885, 0.7999],
        [0.7248, 0.9544, 0.1616],
        [0.1488, 0.1165, 0.9041],
        [0.9522, 0.9528, 0.6864]])


In [16]:
# Addition using '+' sign
print(x + y)

tensor([[1.0672, 1.0855, 1.5021],
        [0.6460, 0.8579, 1.3739],
        [1.5332, 1.4136, 0.8297],
        [0.7518, 0.3084, 1.3044],
        [0.9564, 1.7391, 1.5489]])


In [15]:
# Addition using add function
print(torch.add(x, y))

tensor([[1.0672, 1.0855, 1.5021],
        [0.6460, 0.8579, 1.3739],
        [1.5332, 1.4136, 0.8297],
        [0.7518, 0.3084, 1.3044],
        [0.9564, 1.7391, 1.5489]])


In [18]:
# Store addition in the ouput tensor
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0672, 1.0855, 1.5021],
        [0.6460, 0.8579, 1.3739],
        [1.5332, 1.4136, 0.8297],
        [0.7518, 0.3084, 1.3044],
        [0.9564, 1.7391, 1.5489]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x

In [19]:
# in place addition
y.add_(x)
print(y)

tensor([[1.0672, 1.0855, 1.5021],
        [0.6460, 0.8579, 1.3739],
        [1.5332, 1.4136, 0.8297],
        [0.7518, 0.3084, 1.3044],
        [0.9564, 1.7391, 1.5489]])


In [21]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])
print(x[1, :])

tensor([0.2157, 0.0694, 0.4592, 0.1920, 0.7863])
tensor([0.0395, 0.0694, 0.5740])


In [23]:
# Reshaping
y = x.view(15)
z = x.view(-1, 5)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [24]:
# If you have a one element tensor, use .item() to get the value as a Python number
y = torch.randn(1)
print(y)
print(y.item())

tensor([-0.0317])
-0.031716205179691315


In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
# Change torch tensor to numpy array
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
# Numpy array and torch tensors share memory, changing one will change another (on CPU version)
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [28]:
# Convert numpy array to tensors
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [29]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

### 3. Autograd

In [39]:
# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [40]:
# tensor operation
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [42]:
# more tensor operation
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [43]:
# backpropagation
out.backward()

In [44]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [46]:
# Print gradients d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### 4. Neural Networks

A typical training procedure for a neural network is as follows:
- Define the neural network that has some learnable parameters (or weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule: weight = weight - learning_rate * gradient