This notebook touch upon basics of PyTorch, a polupar deep learning library for defining and training neural networks.

For start, we will import the package called `torch`

In [1]:
import torch

## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [3]:
# define a tensor
scaler = torch.tensor(1)
print(scaler)

tensor(1)


In [4]:
# we can also define a tensor with a list
vector = torch.tensor([1, 2, 3])

# we can also define a tensor with a list of lists
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

vector, matrix

(tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [5]:
# Uninitialized array
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# we can define a tensor with random values
random_matrix = torch.rand(3, 3)
random_matrix

tensor([[0.3311, 0.0904, 0.0078],
        [0.1369, 0.3141, 0.0858],
        [0.8278, 0.8451, 0.3780]])

In [9]:
# check the type of the tensor
# this will tell the type of variable random_matrix
type(random_matrix)

torch.Tensor

In [10]:
# this will tell the type of data the tensor holds
random_matrix.dtype

torch.float32

In [11]:
# we can also specify the data type while defining a tensor
# construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x) 

tensor([[ 2.8661, -1.3088,  0.4643],
        [ 0.0403,  2.6126, -0.0791],
        [-0.0386, -0.8369, -0.3959],
        [ 0.2016, -1.3255, -3.7359],
        [ 0.5319,  0.6995, -0.2352]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
x.shape

torch.Size([5, 3])

## Operations on tensors

In [15]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)

tensor([[0.8120, 0.1492, 0.4794],
        [0.6041, 0.6443, 0.2288],
        [0.8167, 0.7432, 0.7590],
        [0.2053, 0.0927, 0.4814],
        [0.9049, 0.5655, 0.5903]])
tensor([[0.7594, 0.9219, 0.0617],
        [0.0631, 0.3570, 0.6223],
        [0.1765, 0.5563, 0.2319],
        [0.7560, 0.0286, 0.7029],
        [0.2320, 0.4803, 0.0755]])


In [16]:
# Addition using '+' sign
print(x + y)

tensor([[1.5714, 1.0711, 0.5411],
        [0.6672, 1.0013, 0.8511],
        [0.9932, 1.2994, 0.9909],
        [0.9613, 0.1212, 1.1844],
        [1.1370, 1.0458, 0.6658]])


In [17]:
# Addition using add function
print(torch.add(x, y))

tensor([[1.5714, 1.0711, 0.5411],
        [0.6672, 1.0013, 0.8511],
        [0.9932, 1.2994, 0.9909],
        [0.9613, 0.1212, 1.1844],
        [1.1370, 1.0458, 0.6658]])


In [18]:
# Store addition in the ouput tensor
result = torch.zeros(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.5714, 1.0711, 0.5411],
        [0.6672, 1.0013, 0.8511],
        [0.9932, 1.2994, 0.9909],
        [0.9613, 0.1212, 1.1844],
        [1.1370, 1.0458, 0.6658]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x

In [19]:
# in place addition
y.add_(x)
print(y)

tensor([[1.5714, 1.0711, 0.5411],
        [0.6672, 1.0013, 0.8511],
        [0.9932, 1.2994, 0.9909],
        [0.9613, 0.1212, 1.1844],
        [1.1370, 1.0458, 0.6658]])


In [20]:
# You can use standard NumPy-like indexing
print(x[:, 1])
print(x[1, :])

tensor([0.1492, 0.6443, 0.7432, 0.0927, 0.5655])
tensor([0.6041, 0.6443, 0.2288])


In [21]:
# Reshaping
y = x.view(15)
z = x.view(-1, 5)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [22]:
# If you have a one element tensor, use .item() to get the value as a Python number
y = torch.randn(1)
print(y)
print(y.item())

tensor([-0.0538])
-0.05384691432118416


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
# Change torch tensor to numpy array
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
# Numpy array and torch tensors share memory, changing one will change another (on CPU version)
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [26]:
# Convert numpy array to tensors
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [29]:
# let us run this cell only if Apple GPU is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.backends.mps.is_available():
    device = torch.device("mps")  # a Metal Performance Shaders device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("mps")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.float))  # ``.to`` can also change dtype together!

tensor([[1.8120, 1.1492, 1.4794],
        [1.6041, 1.6443, 1.2288],
        [1.8167, 1.7432, 1.7590],
        [1.2053, 1.0927, 1.4814],
        [1.9049, 1.5655, 1.5903]], device='mps:0')
tensor([[1.8120, 1.1492, 1.4794],
        [1.6041, 1.6443, 1.2288],
        [1.8167, 1.7432, 1.7590],
        [1.2053, 1.0927, 1.4814],
        [1.9049, 1.5655, 1.5903]])


## Autograd

In [30]:
# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [31]:
# tensor operation
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [32]:
# more tensor operation
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [33]:
# backpropagation
out.backward()

In [34]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [35]:
# Print gradients d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
